version: '2'
services:
  kafkadb1001:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1001
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1002:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1002
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1003:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1003
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1004:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1004
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1005:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1005
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1006:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1006
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1007:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1007
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
  kafkadb1008:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=1008
      - partitionnumber=384
      - IndexTopic=bmsindex
      - CurrentTopic=bmsdb.historydevices
      - GroupId=bmsgid
    network_mode: "host"
