version: '2'
services:
  kafkadb31:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=431
      - partitionnumber=48
    network_mode: "host"
  kafkadb32:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=432
      - partitionnumber=48
    network_mode: "host"
  kafkadb33:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=433
      - partitionnumber=48
    network_mode: "host"
  kafkadb34:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=434
      - partitionnumber=48
    network_mode: "host"
  kafkadb35:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=435
      - partitionnumber=48
    network_mode: "host"
  kafkadb36:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=436
      - partitionnumber=48
    network_mode: "host"
  kafkadb37:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=437
      - partitionnumber=48
    network_mode: "host"
  kafkadb38:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=438
      - partitionnumber=48
    network_mode: "host"
