version: '2'
services:
  kafkadb321:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=321
      - partitionnumber=384
    network_mode: "host"
  kafkadb322:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=322
      - partitionnumber=384
    network_mode: "host"
  kafkadb323:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=323
      - partitionnumber=384
    network_mode: "host"
  kafkadb324:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=324
      - partitionnumber=384
    network_mode: "host"
  kafkadb325:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=325
      - partitionnumber=384
    network_mode: "host"
  kafkadb326:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=326
      - partitionnumber=384
    network_mode: "host"
  kafkadb327:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=327
      - partitionnumber=384
    network_mode: "host"
  kafkadb328:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - mongos=true
      - NodeID=328
      - partitionnumber=384
    network_mode: "host"
