version: '2'
services:
  zookeeper:
      container_name: zookeeper
      image: zookeeper:3.4.9
      hostname: 192.168.1.136
      restart: always
      network_mode: "host"
      ports:
        - "2181:2181"
      environment:
          ZOO_MY_ID: 3
          ZOO_PORT: 2181
          ZOO_SERVERS: server.1=192.168.1.20:2888:3888 server.2=192.168.1.114:2888:3888 server.3=192.168.1.136:2888:3888
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /catlcluster/zk-multiple-kafka-multiple/zoo/data:/data
        - /catlcluster/zk-multiple-kafka-multiple/zoo/datalog:/datalog
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:4.0.0
    hostname: 192.168.1.136
    restart: always
    network_mode: "host"
    ports:
      - "9092:9092"
    environment:
      # add the entry "127.0.0.1    kafka1" to your /etc/hosts file
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.136:9092"
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIR: "/tmp/kafkalogs"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /catlcluster/zk-multiple-kafka-multiple/kafka/data:/var/lib/kafka/data
      - /catlcluster/zk-multiple-kafka-multiple/kafka/logdir:/tmp/kafkalogs
    depends_on:
      - zookeeper
