version: '2'
services:
  bmsshardres1:
    container_name: bmsshardres1
    image:  mongo:3.4
    restart: always
    command: mongod --shardsvr --replSet bmsshardres1 --dbpath /data/db --port 20001
    ports:
      - 20001:20001
    expose:
      - "20001"
    environment:
      TERM: xterm
    mem_limit: 16384MB
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /catlcluster/mongo_cluster/bmsshardres1/db:/data/db
  bmsshardres2:
    container_name: bmsshardres2
    image:  mongo:3.4
    restart: always
    command: mongod --shardsvr --replSet bmsshardres2 --dbpath /data/db --port 20002
    ports:
      - 20002:20002
    expose:
      - "20002"
    environment:
      TERM: xterm
    mem_limit: 16384MB
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /catlcluster/mongo_cluster/bmsshardres2/db:/data/db
  bmsshardres3:
    container_name: bmsshardres3
    image:  mongo:3.4
    restart: always
    command: mongod --shardsvr --replSet bmsshardres3 --dbpath /data/db --port 20003
    ports:
      - 20003:20003
    expose:
      - "20003"
    environment:
      TERM: xterm
    mem_limit: 16384MB
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /catlcluster/mongo_cluster/bmsshardres3/db:/data/db
  bmsconfigsrv:
    container_name: bmsconfigsrv
    image:  mongo:3.4
    restart: always
    command: mongod --configsvr --replSet bmsconfigsrv --dbpath /data/db --port 27019
    environment:
      TERM: xterm
    ports:
      - 27019:27019
    expose:
      - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/bmsconfigsrv:/data/db
