version: '2'
services:
  kafkadb221:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=221
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb222:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=222
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb223:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=223
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb224:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=224
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb225:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=225
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb226:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=226
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb227:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=227
      - partitionnumber=384
      - IndexTopic=bmsindex
      - GroupId=kafkabmsgroup
    network_mode: "host"
  kafkadb228:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsnew
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=228
      - partitionnumber=384
    network_mode: "host"
