version: '2'
services:
  zookeeper:
      image: wurstmeister/zookeeper
      restart: always
      ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
      KAFKA_CREATE_TOPICS: "BMS.Data:2:2,BMS.bms:2:2,BMS.position:2:2"
      KAFKA_ADVERTISED_HOST_NAME: 118.31.41.232
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
