version: '2'
services:
    mongodb:
      image:  mongo:3.4
      restart: always
      expose:
         - "27018"
      volumes:
         - "/var/db100/dbdata:/data/db -d"
      ports:
         - "27018:27017"
