version: '2'
services:
  nginxbms:
    image: nginx
    restart: always
    ports:
        - "80:8080"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - /root/app/bms/deploy/dist:/usr/share/nginx/bms
        - /root/app/bmscatl/deploy/dist:/usr/share/nginx/bmscatl
  zookeeper:
      image: wurstmeister/zookeeper
      restart: always
      ports:
        - "2181:2181"
