version: '2'
services:
  pkafkadb111:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=111
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb112:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=112
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb113:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=113
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb114:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=114
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb115:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=115
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb116:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=116
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb117:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=117
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
  pkafkadb118:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsp
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=118
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
