version: '2'
services:
  kafkadbtestone1:
    image: node:6.11.2
    restart: always
    command: node --max-old-space-size=8192 ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/kafkadb:/app
      - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
      - /root/bms/deploy/dist/log:/log
    environment:
      - DEBUG=dbh:handler,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bmsptest
      - KAFKA_HOST=192.168.1.20:9092,192.168.1.114:9092,192.168.1.136:9092
      - mongos=true
      - NodeID=777
      - partitionnumber=384
      - kcmsg=1000
      - IndexTopic=pbmsindex
      - CurrentTopic=pbmsindex
      - GroupId=pbmsgid
      - logdir=/log
    network_mode: "host"
