version: '2'
services:
    logserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/bms/deploy/LogServer:/app
      - /root/bms/deploy/dist/log:/log
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
    network_mode: "host"
